name: trafficking_detector
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  
  
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  google_fonts: ^6.2.1
  supabase_flutter: ^2.9.1
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  fpdart: ^1.1.1
  
  
  permission_handler: ^12.0.0+1
  uuid: ^4.5.1
  internet_connection_checker_plus: ^2.7.2
  #firebase_performance: ^0.10.1
  
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  path: ^1.8.2
  geolocator: ^13.0.2
  
  

  #firebase
  # firebase_core: ^3.14.0
  # firebase_auth: ^5.6.0
  # firebase_storage: ^12.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  
  

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 300
       
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight : 300